---
permalink: intro-family.html 
keywords: storagegrid 
summary: NetApp StorageGRID 是一款软件定义的对象存储套件、支持公共、私有和混合多云环境中的各种用例。StorageGRID 为Amazon S3 API提供本机支持、并提供行业领先的创新技术、例如自动化生命周期管理、以便长期经济高效地存储、保护和保留非结构化数据。 
---
= 了解StorageGRID
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp StorageGRID 是一款软件定义的对象存储套件、支持公共、私有和混合多云环境中的各种用例。StorageGRID 为Amazon S3 API提供本机支持、并提供行业领先的创新技术、例如自动化生命周期管理、以便长期经济高效地存储、保护和保留非结构化数据。

StorageGRID 可为大规模非结构化数据提供安全，持久的存储。元数据驱动的集成生命周期管理策略可优化数据在整个生命周期中的位置。将内容放置在合适的位置，合适的时间和合适的存储层上，以降低成本。

StorageGRID 由分布在不同地理位置的冗余异构节点组成，这些节点可以与现有客户端应用程序和下一代客户端应用程序集成在一起。



== StorageGRID 的优势

StorageGRID系统的优势包括：

* 适用于非结构化数据的大规模可扩展且易于使用的地理分布式数据存储库。
* 支持Amazon Web Services Simple Storage Service (S3)协议。
* 已启用混合云。基于策略的信息生命周期管理（ ILM ）可将对象存储到公有 云，包括 Amazon Web Services （ AWS ）和 Microsoft Azure 。StorageGRID 平台服务支持对存储到公有 云的对象进行内容复制，事件通知和元数据搜索。
* 灵活的数据保护，可确保持久性和可用性。可以使用复制和分层纠删编码来保护数据。空闲和正在运行的数据验证可确保完整性，确保长期保留。
* 动态数据生命周期管理，有助于管理存储成本。您可以创建在对象级别管理数据生命周期的 ILM 规则，并自定义数据位置，持久性，性能，成本和保留时间。
* 数据存储和某些管理功能的高可用性，以及集成的负载平衡功能，可优化 StorageGRID 资源中的数据负载。
* 支持多个存储租户帐户，以便按不同实体隔离系统上存储的对象。
* 用于监控 StorageGRID 系统运行状况的众多工具，包括全面的警报系统，图形信息板以及所有节点和站点的详细状态。
* 支持基于软件或硬件的部署。您可以在以下任意位置部署 StorageGRID ：
+
** 在 VMware 中运行的虚拟机。
** Linux 主机上的容器引擎。
** StorageGRID 工程设备。
+
*** 存储设备提供对象存储。
*** 服务设备可提供网格管理和负载平衡服务。




* 符合以下法规的相关存储要求：
+
** 《证券和交易委员会（ SEC ）》，采用 17 § 240.17a-4 （ f ），用于监管交易所成员，代理或交易商。
** 金融行业监管局（ FINRA ）规则 4511 （ c ），该规则符合 SEC 规则 17a-4 （ f ）的格式和介质要求。
** 商品期货交易委员会（ CFTC ）在监管商品期货交易的第 17 条 CFR § 1.31 （ c ） - （ d ）条中进行了规定。


* 无中断升级和维护操作。在升级，扩展，停用和维护过程中保持对内容的访问。
* 联合身份管理。与 Active Directory ， OpenLDAP 或 Oracle Directory Service 集成以进行用户身份验证。支持使用安全断言标记语言 2.0 （ SAML 2.0 ）标准的单点登录（ SSO ），以便在 StorageGRID 和 Active Directory 联合身份验证服务（ AD FS ）之间交换身份验证和授权数据。




== StorageGRID解决方案和资源

前往 https://docs.netapp.com/us-en/storagegrid-enable/index.html["StorageGRID解决方案和资源"^]了解如何在StorageGRID环境中测试和启用应用程序。

* StorageGRID解决方案和资源* 提供了扩展此站点中的产品文档的示例和手册，并描述了评估和集成StorageGRID 的一些后续步骤。

其中一些信息包括：

* 列出了过去和当前StorageGRID 版本中经过验证的第三方解决方案。
* 产品功能指南。例如、这些指南提供了创建云存储池所需的所有信息。
* 工具和应用程序指南。
* 使用S3加密和S3对象锁定等StorageGRID 功能的API示例。

